name: mctg-app
static_sites:
- name: frontend
  github:
    branch: main
    deploy_on_push: true
  build_command: npm run build
  output_dir: dist
  routes:
  - path: /
  catchall_document: index.html
  error_document: index.html
